name: Deploy to GitHub Pages via angular-cli-ghpages

on:
  push:
    branches: [ "master" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Prepare and deploy
        run: |
          npm install
          npm run ng -- deploy --base-href=/portfolio/
